name: Upload release artefacts

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - id: vars
      run: echo ::set-output name=tag::${GITHUB_REF:10}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.15.x'
        channel: 'dev'
    - name: Copy secrets
      run: |
        cd android/app
        echo ${{ secrets.KEYSTORE_B64 }} | base64 -d | zcat >> 15puzzle-release.jks
        echo ${{ secrets.KEYSTORE_PROPS_B64 }} | base64 -d | zcat >> 15puzzle-release.properties
        cd ..
        cd ..
    - name: Upgrade flutter
      run: flutter upgrade
    - name: Enable web
      run: flutter config --enable-web
    - name: Install dependencies
      run: flutter packages get
    - name: Build
      run: |
        flutter build web
        flutter build appbundle --release --flavor=playStore
    - name: Compress web
      run: |
        cd build
        zip -r web.zip web
        cd ..
        mv build/web.zip web.zip
    - name: Deploy web
      run: |
        cd build/web
        git init
        git config user.name  "Artem Bot"
        git config user.email "artemchep@gmail.com"
        git remote add rorigin https://${{ secrets.TOKEN }}@github.com/AChep/15puzzle.git
        git checkout -b gh-pages
        git add .
        git commit -m "Updated web build"
        git push --force rorigin gh-pages
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload release web
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: web.zip
        asset_name: 15puzzle-web-${{ steps.vars.outputs.tag }}.zip
        asset_content_type: application/zip
    - name: Upload release android-aab
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/bundle/playStoreRelease/app-playStore-release.aab
        asset_name: 15puzzle-android-${{ steps.vars.outputs.tag }}.aab
        asset_content_type: application/zip
